// CGFloat+Converter.swift
// Deliria
//
// Created by Yanke Guo on 16/2/10.
// Generated by KissShot https://github.com/YMXian/kiss_shot
//
// Copyright © 2016年 JuXian(Beijing) Technology Co., Ltd. All rights reserved.
//

import CoreGraphics

extension CGFloat {

  /// Convert self:CGFloat to Int
  public var Int: Swift.Int {
    return Swift.Int(self)
  }

  /// Convert self:CGFloat to Double
  public var Double: Swift.Double {
    return Swift.Double(self)
  }

  /// Convert self:CGFloat to Float
  public var Float: Swift.Float {
    return Swift.Float(self)
  }

  /// Returns self
  public var CGFloat: CoreGraphics.CGFloat {
    return self
  }

}

extension Int {

  /// Convert Int to CGFloat
  public var CGFloat: CoreGraphics.CGFloat {
    return CoreGraphics.CGFloat(self)
  }

}

extension Double {

  /// Convert Double to CGFloat
  public var CGFloat: CoreGraphics.CGFloat {
    return CoreGraphics.CGFloat(self)
  }

}

extension Float {

  /// Convert Float to CGFloat
  public var CGFloat: CoreGraphics.CGFloat {
    return CoreGraphics.CGFloat(self)
  }

}
