// NumericTypes+Converter.swift
// Deliria
//
// Created by Yanke Guo on 16/2/10.
// Generated by KissShot https://github.com/YMXian/kiss_shot
//
// Copyright © 2016年 JuXian(Beijing) Technology Co., Ltd. All rights reserved.
//

extension Int {

  /// Returns self
  public var Int: Swift.Int {
    return self
  }

  /// Convert self:Int to UInt
  public var UInt: Swift.UInt {
    return Swift.UInt(self)
  }

  /// Convert self:Int to Double
  public var Double: Swift.Double {
    return Swift.Double(self)
  }

  /// Convert self:Int to Float
  public var Float: Swift.Float {
    return Swift.Float(self)
  }

}

extension UInt {

  /// Convert self:UInt to Int
  public var Int: Swift.Int {
    return Swift.Int(self)
  }

  /// Returns self
  public var UInt: Swift.UInt {
    return self
  }

  /// Convert self:UInt to Double
  public var Double: Swift.Double {
    return Swift.Double(self)
  }

  /// Convert self:UInt to Float
  public var Float: Swift.Float {
    return Swift.Float(self)
  }

}

extension Double {

  /// Convert self:Double to Int
  public var Int: Swift.Int {
    return Swift.Int(self)
  }

  /// Convert self:Double to UInt
  public var UInt: Swift.UInt {
    return Swift.UInt(self)
  }

  /// Returns self
  public var Double: Swift.Double {
    return self
  }

  /// Convert self:Double to Float
  public var Float: Swift.Float {
    return Swift.Float(self)
  }

}

extension Float {

  /// Convert self:Float to Int
  public var Int: Swift.Int {
    return Swift.Int(self)
  }

  /// Convert self:Float to UInt
  public var UInt: Swift.UInt {
    return Swift.UInt(self)
  }

  /// Convert self:Float to Double
  public var Double: Swift.Double {
    return Swift.Double(self)
  }

  /// Returns self
  public var Float: Swift.Float {
    return self
  }

}
