#!/usr/bin/env ruby

require 'kiss_shot'

types = [:Int, :UInt, :Double, :Float]

content = KissShot::Spec.run do
  line "// NumericTypes+Converter.swift"
  line "// Deliria"
  line "//"
  line "// Created by Yanke Guo on 16/2/10."
  line "// Generated by KissShot https://github.com/YMXian/kiss_shot"
  line "//"
  line "// Copyright © 2016年 JuXian(Beijing) Technology Co., Ltd. All rights reserved."
  line "//"

  types.each do |type|
    line
    line "extension #{type} {"

    types.each do |type2|
      line
      indent_up

      if type2.to_s == type.to_s
        line "/// Returns self"
      else
        line "/// Convert self:#{type} to #{type2}"
      end

      line "public var #{type2}: Swift.#{type2} {"
      indent_up
      if type2.to_s == type.to_s
        line "return self"
      else
        line "return Swift.#{type2}(self)"
      end
      indent_down
      line "}"
      indent_down
    end

    line
    line "}"
  end
end

puts content
